// Generated by hec.py — JavaScript backend
(function(){
  // Runtime checks: True

  class Genesis {
    constructor() {
    }

    greetings() {
      // raw: greeting: string = Hello World
    }

    Actions() {
    }

    SayHello(name) {
      if (typeof name !== "string") throw new TypeError("Expected string for name");
      console.log(this.greeting);
      document.body.innerHTML += '<pre>' + String(this.greeting) + '</pre>';
      console.log(this.name);
      document.body.innerHTML += '<pre>' + String(this.name) + '</pre>';
    }

  }

  const __main = new Genesis();
  if (typeof __main.greetings === 'function') __main.greetings();
})();