package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"hunterlang/lang/eval"
	"hunterlang/lang/lexer"
	"hunterlang/lang/parser"
)

func main() {
	serveMode := flag.Bool("serve", false, "Run a local dev server")
	addr := flag.String("addr", "http://localhost:8080", "Server address (host:port or full URL)")
	inputPath := flag.String("file", "", "Path to .he file")

	siteMode := flag.Bool("site", false, "Serve a docs/site generated by running -sitefile")
	siteFile := flag.String("sitefile", "docs.he", "Path to .he file that prints full HTML for the site")

	flag.Parse()

	if *inputPath == "" && !*siteMode {
		fmt.Fprintln(os.Stderr, "Usage:")
		fmt.Fprintln(os.Stderr, "  hunterlang -file path/to/game.he")
		fmt.Fprintln(os.Stderr, "  hunterlang -serve -file path/to/game.he [-addr localhost:8080]")
		fmt.Fprintln(os.Stderr, "  hunterlang -serve -site -sitefile path/to/docs.he [-addr localhost:8080]")
		os.Exit(2)
	}

	if *serveMode {
		if *addr == "" {
			*addr = "http://localhost:8080"
		}
		// net/http ListenAndServe expects host:port, so strip scheme if present.
		listenAddr := *addr
		if strings.HasPrefix(listenAddr, "http://") {
			listenAddr = strings.TrimPrefix(listenAddr, "http://")
		} else if strings.HasPrefix(listenAddr, "https://") {
			listenAddr = strings.TrimPrefix(listenAddr, "https://")
		}

		st := &serveState{}
		if err := startServe(listenAddr, *inputPath, *siteMode, *siteFile, st); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		return
	}

	// CLI mode: run once and print stdout directly.
	b, err := os.ReadFile(*inputPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, "read file:", err)
		os.Exit(1)
	}

	// Strip UTF-8 BOM if present: EF BB BF
	if len(b) >= 3 && b[0] == 0xEF && b[1] == 0xBB && b[2] == 0xBF {
		b = b[3:]
	}

	src := string(b)

	lx := lexer.New(src)
	p := parser.New(lx)

	prog, err := p.ParseProgram()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	interpreter := eval.NewInterpreter()
	if err := interpreter.Run(prog); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
