// src/main/kotlin/compiler/KotlinCompiler.kt
package compiler

import ast.*

class KotlinCompiler {
    private val output = StringBuilder()
    private var indentLevel = 0
    private val commentRegistry = mutableMapOf<Int, String>()
    
fun compile(program: Program): String {
    output.clear()
    
    generateHeader()
    
    program.lines.forEach { line ->
        when (line) {
            is SummonLine -> compileSummon(line)
            is WithAssetsLine -> compileWithAssets(line)
            is ObjectDef -> compileObject(line)
            // No CommentLine anymore
        }
    }
    
    return output.toString()
}
    
    private fun collectComments(program: Program) {
        program.lines.forEachIndexed { index, line ->
            if (line is CommentLine) {
                commentRegistry[index] = line.text
            }
        }
    }
    
    private fun compileComment(commentText: String) {
        val kotlinComment = when {
            commentText.contains('\n') -> {
                // Multi-line comment
                val lines = commentText.lines()
                if (lines.size == 1) {
                    "/* ${lines[0]} */"
                } else {
                    val comment = StringBuilder("/*\n")
                    lines.forEach { line ->
                        indent { comment.appendLine(" * $line") }
                    }
                    indent { comment.append(" */") }
                    comment.toString()
                }
            }
            else -> {
                // Single-line comment
                indent { "// $commentText" }
            }
        }
        output.appendLine(kotlinComment)
    }
    
    private fun generateHeader() {
        output.appendLine("""
            // ===================================================================
            // Generated by HE_New Compiler
            // DO NOT EDIT - This file was automatically generated
            // ===================================================================
            
            @file:Suppress("unused", "ClassName", "MemberVisibilityCanBePrivate")
            
            import kotlinx.coroutines.*
            import kotlinx.coroutines.Dispatchers
            import kotlinx.coroutines.withContext
            
            // ===================================================================
            // Basic Game Framework
            // ===================================================================
            
            /**
             * Base class for all game objects.
             */
            open class GameObject {
                protected val assets = mutableMapOf<String, Any>()
                protected var running = true
                
                fun setAsset(name: String, asset: Any) {
                    assets[name] = asset
                }
                
                fun getAsset(name: String): Any? = assets[name]
                
                suspend fun gameLoop() {
                    while (running) {
                        update()
                        delay(16) // ~60 FPS
                    }
                }
                
                open fun update() { }
                
                open suspend fun show(asset: String, centered: Boolean = false) {
                    println("Showing asset: \$asset" + if (centered) " (centered)" else "")
                }
            }
            
            // ===================================================================
            // Asset Loading System
            // ===================================================================
            
            /**
             * Interface for loading game assets on different platforms.
             */
            interface AssetLoader {
                fun loadImage(path: String): Any
                fun loadSound(path: String): Any
                fun loadMusic(path: String): Any
                fun loadFont(path: String): Any
                fun loadShader(path: String): Any
            }
            
            /**
             * Default asset loader implementation.
             * Override this for different platforms (Android, iOS, Desktop, Web).
             */
            object DefaultAssetLoader : AssetLoader {
                override fun loadImage(path: String): Any = ImageAsset(path)
                override fun loadSound(path: String): Any = SoundAsset(path)
                override fun loadMusic(path: String): Any = MusicAsset(path)
                override fun loadFont(path: String): Any = FontAsset(path)
                override fun loadShader(path: String): Any = ShaderAsset(path)
            }
            
            // Simple asset wrappers
            data class ImageAsset(val path: String)
            data class SoundAsset(val path: String)
            data class MusicAsset(val path: String)
            data class FontAsset(val path: String)
            data class ShaderAsset(val path: String)
            
            // Global asset loader instance
            val assetLoader: AssetLoader = DefaultAssetLoader
            
            // ===================================================================
            // Helper Extensions
            // ===================================================================
            
            /**
             * Extension function to center display.
             */
            fun Any.centered(): Any {
                println("Centering: \$this")
                return this
            }
            
            /**
             * Simplified delay function.
             */
            suspend fun delaySeconds(seconds: Double) {
                delay((seconds * 1000).toLong())
            }
            
            // ===================================================================
            // Generated Game Code Starts Below
            // ===================================================================
            
        """.trimIndent())
        output.appendLine()
    }
    
    private fun compileSummon(summon: SummonLine) {
        output.appendLine("// Summoned entity: ${summon.type}")
        indent {
            output.appendLine("object ${summon.name} : ${summon.type.replaceFirstChar { it.uppercase() }}() {")
            indentLevel++
            output.appendLine("// TODO: Implement ${summon.type} functionality")
            indentLevel--
            output.appendLine("}")
        }
        output.appendLine()
    }
    
    private fun compileWithAssets(withAssets: WithAssetsLine) {
        if (withAssets.assets.isNotEmpty()) {
            output.appendLine("// Load game assets")
        }
        
        withAssets.assets.forEach { asset ->
            val loaderMethod = when (asset.type) {
                AssetType.IMAGE -> "loadImage"
                AssetType.SOUND -> "loadSound"
                AssetType.MUSIC -> "loadMusic"
                AssetType.FONT -> "loadFont"
                AssetType.SHADER -> "loadShader"
                else -> "loadImage"
            }
            
            val assetName = asset.name ?: generateAssetName(asset.path)
            val assetType = when (asset.type) {
                AssetType.IMAGE -> "ImageAsset"
                AssetType.SOUND -> "SoundAsset"
                AssetType.MUSIC -> "MusicAsset"
                AssetType.FONT -> "FontAsset"
                AssetType.SHADER -> "ShaderAsset"
                else -> "Any"
            }
            
            indent {
                output.appendLine("val $assetName: $assetType = assetLoader.$loaderMethod(\"${asset.path}\")")
            }
        }
        
        if (withAssets.assets.isNotEmpty()) {
            output.appendLine()
        }
    }
    
    private fun compileObject(obj: ObjectDef) {
        val parentClass = obj.parent ?: "GameObject"
        
        output.appendLine("// ===================================================================")
        output.appendLine("// ${obj.name} - Game Object")
        output.appendLine("// ===================================================================")
        output.appendLine()
        
        output.appendLine("class ${obj.name} : $parentClass() {")
        indentLevel++
        
        // Check for properties sections
        val propertySections = obj.body.sections.filterIsInstance<PropertiesSection>()
        if (propertySections.isNotEmpty()) {
            output.appendLine()
            output.appendLine("    // ===========================================================")
            output.appendLine("    // Properties")
            output.appendLine("    // ===========================================================")
            output.appendLine()
        }
        
        // Compile properties as fields
        propertySections.flatMap { it.properties }
            .forEach { prop ->
                indent { 
                    val comment = if (prop.value is StringLiteral) " // \"${(prop.value as StringLiteral).value}\"" 
                                 else if (prop.value is NumberLiteral) " // ${(prop.value as NumberLiteral).value}"
                                 else ""
                    output.appendLine("var ${prop.name} = ${compileExpression(prop.value)}$comment")
                }
            }
        
        // Check for abilities sections
        val abilitySections = obj.body.sections.filterIsInstance<AbilitiesSection>()
        if (abilitySections.isNotEmpty()) {
            output.appendLine()
            output.appendLine("    // ===========================================================")
            output.appendLine("    // Abilities")
            output.appendLine("    // ===========================================================")
            output.appendLine()
        }
        
        // Compile abilities (methods)
        abilitySections.flatMap { it.methods }
            .forEach { method ->
                compileMethod(method)
            }
        
        // Check for reaction sections
        val reactionSections = obj.body.sections.filterIsInstance<ReactionSection>()
        if (reactionSections.isNotEmpty()) {
            output.appendLine()
            output.appendLine("    // ===========================================================")
            output.appendLine("    // Event Reactions")
            output.appendLine("    // ===========================================================")
            output.appendLine()
        }
        
        // Compile reactions
        reactionSections.forEach { reaction ->
            compileReaction(reaction)
        }
        
        // Add default constructor if needed
        if (propertySections.isNotEmpty()) {
            output.appendLine()
            indent {
                output.appendLine("// Default constructor")
                output.appendLine("constructor() : super()")
            }
        }
        
        indentLevel--
        output.appendLine("}")
        output.appendLine()
    }
    
    private fun compileMethod(method: Method) {
        indent {
            val params = method.params.joinToString(", ") { "${it.name}: ${it.type.toKotlinType()}" }
            val paramDoc = if (method.params.isNotEmpty()) {
                method.params.joinToString("\n") { param ->
                    "     * @param ${param.name} ${param.type.toKotlinType().lowercase()} parameter"
                }
            } else ""
            
            // Method documentation
            output.appendLine("/**")
            output.appendLine(" * ${method.name} method.")
            if (paramDoc.isNotEmpty()) {
                output.appendLine(paramDoc)
            }
            output.appendLine(" */")
            
            // Method signature
            output.appendLine("fun ${method.name}($params) {")
            indentLevel++
            
            // Method body
            if (method.body.isNotEmpty()) {
                method.body.forEach { stmt ->
                    compileStatement(stmt)
                }
            } else {
                indent { output.appendLine("// TODO: Implement ${method.name}") }
            }
            
            indentLevel--
            output.appendLine("}")
        }
        output.appendLine()
    }
    
    private fun compileReaction(reaction: ReactionSection) {
        indent {
            val eventName = reaction.event.replaceFirstChar { it.uppercase() }
            
            output.appendLine("/**")
            output.appendLine(" * Called when '${reaction.event}' event occurs.")
            output.appendLine(" */")
            output.appendLine("fun on$eventName() {")
            indentLevel++
            
            reaction.statements.forEach { stmt ->
                compileStatement(stmt)
            }
            
            indentLevel--
            output.appendLine("}")
        }
        output.appendLine()
    }
    
    private fun compileStatement(stmt: Statement) {
        indent {
            when (stmt) {
                is PrintStmt -> {
                    output.appendLine("println(${compileExpression(stmt.expression)})")
                }
                is CallStmt -> {
                    val args = stmt.args.joinToString(", ") { compileExpression(it) }
                    val methodCall = if (args.isNotEmpty()) {
                        "${stmt.target}.${stmt.method}($args)"
                    } else {
                        "${stmt.target}.${stmt.method}()"
                    }
                    output.appendLine(methodCall)
                }
                is ShowStmt -> {
                    if (stmt.centered) {
                        output.appendLine("show(${stmt.asset}.centered())")
                    } else {
                        output.appendLine("show(${stmt.asset})")
                    }
                }
                is WaitStmt -> {
                    output.appendLine("delaySeconds(${compileExpression(stmt.duration)})")
                }
                is AssignmentStmt -> {
                    output.appendLine("${stmt.name} = ${compileExpression(stmt.value)}")
                }
            }
        }
    }
    
    private fun compileExpression(expr: Expression): String = when (expr) {
        is StringLiteral -> "\"${escapeString(expr.value)}\""
        is NumberLiteral -> expr.value.toString()
        is Identifier -> expr.name
        is BinaryExpression -> {
            val left = compileExpression(expr.left)
            val right = compileExpression(expr.right)
            val op = when (expr.operator) {
                "+" -> " + "
                "-" -> " - "
                "*" -> " * "
                "/" -> " / "
                else -> " ${expr.operator} "
            }
            "($left$op$right)"
        }
        else -> "null"
    }
    
    private fun escapeString(value: String): String {
        return value.replace("\\", "\\\\")
                   .replace("\"", "\\\"")
                   .replace("\n", "\\n")
                   .replace("\t", "\\t")
    }
    
    private fun Type.toKotlinType(): String = when (this) {
        Type.STRING -> "String"
        Type.NUMBER -> "Double"
        Type.BOOLEAN -> "Boolean"
    }
    
    private fun indent(block: () -> Unit) {
        val indent = "    ".repeat(indentLevel)
        output.append(indent)
        block()
    }
    
    private fun generateAssetName(path: String): String {
        val fileName = path.substringAfterLast('/').substringBeforeLast('.')
        return fileName.replace(Regex("[^a-zA-Z0-9_]"), "_")
                      .replaceFirstChar { it.lowercase() }
    }
}